#############################################################################
# Makefile for building: bin/stbtest
# Generated by qmake (2.01a) (Qt 4.6.0) on: ?? ???. 24 23:28:01 2011
# Project:  stbtest.pro
# Template: app
# Command: /usr/local/Trolltech/QtEmbedded-4.6.0-generic/bin/qmake -spec /usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/qws/linux-sh4-g++ -unix -o Makefile stbtest.pro
#############################################################################

####### Compiler, tools and options

CC            = sh4-linux-gnu-gcc
CXX           = sh4-linux-gnu-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/qws/linux-sh4-g++ -I. -I/usr/local/Trolltech/QtEmbedded-4.6.0-generic/include/QtCore -I/usr/local/Trolltech/QtEmbedded-4.6.0-generic/include/QtNetwork -I/usr/local/Trolltech/QtEmbedded-4.6.0-generic/include/QtGui -I/usr/local/Trolltech/QtEmbedded-4.6.0-generic/include -Iheaders -I../X-sh4/include -Imoc -Iuic
LINK          = sh4-linux-gnu-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/QtEmbedded-4.6.0-generic/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEmbedded-4.6.0-generic/lib -L/home/kirdyk/X-sh4/lib -lstbplayer -lvmclient -lSecureMedia -lfilter-cas -lavformat -lavcodec -llirc_client -lavutil -lavcore -lfreetype -lz -lQtGui -L/usr/local/Trolltech/QtEmbedded-4.6.0-generic/lib -ldirect -ldirectfb -lfusion -lQtNetwork -lQtCore -lpthread 
AR            = sh4-linux-gnu-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/QtEmbedded-4.6.0-generic/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = sh4-linux-gnu-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/dialog.cpp moc/moc_mainwindow.cpp \
		moc/moc_dialog.cpp
OBJECTS       = obj/main.o \
		obj/mainwindow.o \
		obj/dialog.o \
		obj/moc_mainwindow.o \
		obj/moc_dialog.o
DIST          = /usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/lex.prf \
		stbtest.pro
QMAKE_TARGET  = stbtest
DESTDIR       = bin/
TARGET        = bin/stbtest

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): uic/ui_mainwindow.h uic/ui_dialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: stbtest.pro  /usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/qws/linux-sh4-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/lib/libQtGui.prl \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/lib/libQtNetwork.prl \
		/usr/local/Trolltech/QtEmbedded-4.6.0-generic/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/qws/linux-sh4-g++ -unix -o Makefile stbtest.pro
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/g++.conf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/release.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/lib/libQtGui.prl:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/lib/libQtNetwork.prl:
/usr/local/Trolltech/QtEmbedded-4.6.0-generic/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.6.0-generic/mkspecs/qws/linux-sh4-g++ -unix -o Makefile stbtest.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/stbtest1.0.0 || $(MKDIR) obj/stbtest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/stbtest1.0.0/ && $(COPY_FILE) --parents headers/mainwindow.h headers/dialog.h obj/stbtest1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/dialog.cpp obj/stbtest1.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui ui/dialog.ui obj/stbtest1.0.0/ && (cd `dirname obj/stbtest1.0.0` && $(TAR) stbtest1.0.0.tar stbtest1.0.0 && $(COMPRESS) stbtest1.0.0.tar) && $(MOVE) `dirname obj/stbtest1.0.0`/stbtest1.0.0.tar.gz . && $(DEL_FILE) -r obj/stbtest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_mainwindow.cpp moc/moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_mainwindow.cpp moc/moc_dialog.cpp
moc/moc_mainwindow.cpp: headers/mainwindow.h
	/usr/local/Trolltech/QtEmbedded-4.6.0-generic/bin/moc $(DEFINES) $(INCPATH) headers/mainwindow.h -o moc/moc_mainwindow.cpp

moc/moc_dialog.cpp: headers/dialog.h
	/usr/local/Trolltech/QtEmbedded-4.6.0-generic/bin/moc $(DEFINES) $(INCPATH) headers/dialog.h -o moc/moc_dialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: uic/ui_mainwindow.h uic/ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) uic/ui_mainwindow.h uic/ui_dialog.h
uic/ui_mainwindow.h: ui/mainwindow.ui
	/usr/local/Trolltech/QtEmbedded-4.6.0-generic/bin/uic ui/mainwindow.ui -o uic/ui_mainwindow.h

uic/ui_dialog.h: ui/dialog.ui
	/usr/local/Trolltech/QtEmbedded-4.6.0-generic/bin/uic ui/dialog.ui -o uic/ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/mainwindow.o: src/mainwindow.cpp uic/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainwindow.o src/mainwindow.cpp

obj/dialog.o: src/dialog.cpp headers/dialog.h \
		uic/ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/dialog.o src/dialog.cpp

obj/moc_mainwindow.o: moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainwindow.o moc/moc_mainwindow.cpp

obj/moc_dialog.o: moc/moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_dialog.o moc/moc_dialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

